services:
  postgres:
    image: postgres:15-alpine
    container_name: ecfr-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ecfr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecfr-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ecfr
      - RUN_INGESTION=false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: bash -c "ls -la entrypoint.sh && bash entrypoint.sh"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
